Repository bermarte/duck-duck-clone, pull requests merged in 2020-10, with the labels that each got.

#10 Wireframe
  development-strategy.md
  imgs/wireframe.pdf
  imgs/wireframe.png
Labels: documentation

#12 Creating the alpinist section
  css/style.css
  index.html
Labels: enhancement

#16 add bathtub section
  css/style.css
  index.html
Labels: enhancement

#9 Section ghost
  css/style.css
  index.html
Labels: enhancement

#20 Mods
  css/style.css
  imgs/teaser-2@2x.png
  index.html
  js/index.js
Labels: bug, enhancement
